### ISSUE TITLE
PC-Link support

### ISSUE THREAD

**Issue by e474** [kbr-net/sdrive-max#13]
Hi,

   Can you add PC-LINK protocol support (example C code for PC-LINK support is in SIO2BSD at http://drac030.krap.pl/en-inne-pliki.php )?

**Comment by kbr-net** [comment]
Well, we have a touchscreen, it would be much easier to add more functions there.

**Comment by kbr-net** [comment]
I don't want to add this, because it is too much work, and too less benefit in my opinion.
Otherways the flash is nearly full.
