### ISSUE TITLE
Physical Drive Disk Copy Question

### ISSUE THREAD

**Issue by iCityWork** [kbr-net/sdrive-max#15]
Greetings! First of all, thank you for your hard work with this, I love using my SDrive-MAX to load up old images and relive my childhood with my original Atari 800 computer that the drive allows me to do. I do have a question though about copying my old floppies to the SDrive-MAX.  If I boot to my physical drive and have my SDrive-MAX attached with a blank image loaded on D2 can I copy my files from my floppy drive to the blank image in order to keep them on SD cards in case of original floppy failure?  
If so, how can I go about doing this? What do I need to do to the SDrive-MAX so I can copy files from my physical drive over too it? Do I boot to the SDrive and have my physical drive as D2? 
Thanks for help/guidance and Happy New Year!
Gavin

**Comment by no1453** [comment]
The best solution I found was to use a sector copier on the Atari.   You boot a sector copier from an image on the SDrive-MAX, then mount a blank image in the SD-M (as, say. D1:), and use the sector copier to copy all the data from the physical disk to the blank image.   You just need to configure the physical drive as D2, in this example.

**Comment by iCityWork** [comment]
So boot to SDrive-MAX and have the physical drive as D2?  I need to find a good sector copier.  I used to have all this stuff back in the day, but that was 35 years ago.

**Comment by kbr-net** [comment]
There was no further question yet.

**Comment by Back2skooldaze** [comment]
What I've done is my 1050 drive as D1: on my sd drive max I've put a new in D2: load spartados on 1050 then xinit D2: don't use ultraskew then format D2: in the sd drive max. Once that's done you can use Xcopy in spartados to copy a floppy from 1050 to sd drive max D2: 
Transferring from sd drive max to floppy you change your 1050 to D2: and set sd drive max to D1: load spartados on sd drive max DONT USE UKTRASKEW when formatting 1050 floppy and then use Xcopy then eject D1: in sd drive max load a game then copy across!! Simple I have done this and it works!!!
Remember you need the breakout board inside your sd drive max to communicate with SIO devices.
