### ISSUE TITLE
Screen Colour inverted? atmega328-ili9340

### ISSUE THREAD

**Issue by mamejay** [kbr-net/sdrive-max#18]
I am using the atmega328-ili9340 which is the only one that works with my display.  The background is white.
When i tested with the other builds the background is black.  Is there anyway to invert the colours on this build?
Thanks

**Comment by kbr-net** [comment]
Have you testet the latest beta release 1.2b1?

**Comment by mamejay** [comment]
Yes but it would not work.
My screen is a atmega328-ili9340 and the 12b1 version says its for atmega328-hx8347d
The other versions are the correct colour but the touch screen does not work

**Comment by mamejay** [comment]
atmega328-ili9329 works with correct colours but all text is mirrored/back to front.

**Comment by kbr-net** [comment]
Why are you sure, it is an ili9340?
ili9341looks correct, except touchscreen?

**Comment by mamejay** [comment]
I went through each folder and tested installing.  The only version that gave me a readable screen and working touch was the ili9340.
ili9341 gives me correct colour but I cannot calibrate the screen and the atmega328-ili932 lets me calibrate but everything is mirrored.

**Comment by kbr-net** [comment]
What ID is shown shortly after power up?

**Comment by mamejay** [comment]
Its flashes up so fast but looks like c3c3

**Comment by kbr-net** [comment]
Weird. If i make a Version with ili9341 screen and ili9340 touch, this would be correct?

**Comment by mamejay** [comment]
I suspect that should work.  I just wrote the ili9341 code back on and can read the ID better.  d3d3.

**Comment by kbr-net** [comment]
mcufriend_kbv says:

>     if (ret == 0x00D3 || ret == 0xD3D3)
> return ret; //16-bit write-only bus

Are you sure it is a 8bit?

**Comment by mamejay** [comment]
I am not sure.  Was just a screen I purchased from Banggood.  d3d3 is what shows up on bootup

**Comment by kbr-net** [comment]
Try this:
[sdrive-max-v12b2.zip](https://github.com/kbr-net/sdrive-max/files/3481413/sdrive-max-v12b2.zip)

**Comment by mamejay** [comment]
> 
> 
> Try this:
> [sdrive-max-v12b2.zip](https://github.com/kbr-net/sdrive-max/files/3481413/sdrive-max-v12b2.zip)

Perfect!  That works as expected now.  Thank you very much

**Comment by kbr-net** [comment]
Ok, i am thinking about the final integration, maybe i will add an autodetection for the touchscreen, then you could use the ili9341 in future...

**Comment by mamejay** [comment]
If you need me to test let me know

**Comment by kbr-net** [comment]
You are welcome!

**Comment by kbr-net** [comment]
Please try https://github.com/kbr-net/sdrive-max/releases/download/v12c2/sdrive-max-v12c2.zip

**Comment by TzOk83** [comment]
Touchscreen still doesn't work.

**Comment by kbr-net** [comment]
> Please try https://github.com/kbr-net/sdrive-max/releases/download/v12c2/sdrive-max-v12c2.zip

this version was buggy, please wait for v12c3, and then try this...

**Comment by mamejay** [comment]
Think this one can be closed.  Everything seems to be working correctly
