### ISSUE TITLE
No touch on a 9340

### ISSUE THREAD

**Issue by mamejay** [kbr-net/sdrive-max#19]
Got a couple of bonus smaller 2" screens with an order
I have tested with the different firmware but cannot get the touch to work.
The ID that appears on boot is 9340
If I use the atmega328-ili9340 the colour is correct but the picture is inverted and touch does not work.  It lets me calibrate but does not register anything after that.
Anyway to test to work out what touch is required?

**Comment by kbr-net** [comment]
Have you tried the special pre-release V1.2b?

Install the arduino IDE and try this sketch: https://github.com/prenticedavid/MCUFRIEND_kbv/blob/master/examples/diagnose_Touchpins/diagnose_Touchpins.ino

**Comment by kbr-net** [comment]
Or try the firmware in this issue below: https://github.com/kbr-net/sdrive-max/issues/18

**Comment by mamejay** [comment]
Thanks for that.  I have tried all the firmware that is available.  I have tried the diagnose_touchpins sketch but I just get a blank screen.  Am I supposed to connect this to a serial connection to read the results?

**Comment by kbr-net** [comment]
Yes, this only examines the touchscreen lines, there is no display output. Just open the serial monitor on the arduino IDE.

**Comment by kbr-net** [comment]
Done in issue #18
