### ISSUE TITLE
LED

### ISSUE THREAD

**Issue by iCityWork** [kbr-net/sdrive-max#20]
Are there any ports on the Arduino that I could hook LED's to in order to have a drive activity LED? Working on an 810 enclosure and would love to have the two LEDs on the front functional.
Thanks,
Gavin

**Comment by kbr-net** [comment]
Would be difficult, because all ports are in use.

**Comment by iCityWork** [comment]
There is no way to piggyback on one of them to drive the LED?

**Comment by kbr-net** [comment]
The only way i see, the PLCC-Version of atmega328 has 2 more ports, which are not assigned to pins, they could be used.

**Comment by kbr-net** [comment]
An other idea is to use the SD cards chip select line(Pin 10) to drive a led with, but this will be very short flashes.

**Comment by Mi1ezDR** [comment]
I'm still a circuit noob but couldn't you could use a capacitor to help keep the LED's lit for a little longer (milliseconds) until the capacitor has emptied out so that you have a visual chance to see it's been working?

**Comment by kbr-net** [comment]
Just try it!

**Comment by TzOk83** [comment]
Actually the USER_LED, which is hooked to the PIN 13 (PB5), is nicely blinking when there is a drive activity. It is the SD-card's CLK line (SD_SCK).
