### ISSUE TITLE
XPT2046 touchscreen support

### ISSUE THREAD

**Issue by TzOk83** [kbr-net/sdrive-max#26]
There are quite popular ILI9341+XPT2046 TFT touchscreens available. Would you consider adding support for this touch controller chip?

**Comment by bweiser** [comment]
The ILI9341 has support for it already.

**Comment by TzOk83** [comment]
I realize too late that you only support ILI9341 over a parallel link, and not over SPI. XPT2046 is an SPI touch (digitizer) screen controller, commonly used in SPI TFT screens based on ILI9341 chips. Your code supports only direct (analog) signals from digitizer screen, but in case it doesn't support SPI mode for graphics, there is probably no point to support SPI touch sensor.

**Comment by kbr-net** [comment]
Yes, this would be too difficult, and would be like a completely rewrite of the firmware.
