### ISSUE TITLE
support for reading baud

### ISSUE THREAD

**Issue by ascrnet** [kbr-net/sdrive-max#35]
So check the sources when reading a .cas file ignore the baud tag and place it in 600 baud which is the standard. It would be ideal if you read the label and let the baud be set according to the .cas file as emulators or real atari do
I leave 3 .cas test files that work, but not in the sdrive
https://www.atariware.cl/archivos/sdrive-max/cas_baud.zip
Or will it be very complicated to implement?
regards

**Comment by kbr-net** [comment]
This should be possible, i will see...

**Comment by kbr-net** [comment]
Is included in the next release V12.
