### ISSUE TITLE
Documentation for sdrive.com??? anywhere?

### ISSUE THREAD

**Issue by jedimatt42** [kbr-net/sdrive-max#36]
I can't locate end user documentation for sdrive.com...  I thought it was built into the program.. but then I can't remember how to view it either.. 

Something in the README.md pointing to those docs would be good.

**Comment by ascrnet** [comment]
> 
> 
> I can't locate end user documentation for sdrive.com... I thought it was built into the program.. but then I can't remember how to view it either..
> 
> Something in the README.md pointing to those docs would be good.

Read the following pdf contains the keys SDRIVE.COM 
https://atari8bit.net/wp-content/uploads/SDrive_en.pdf

**Comment by kbr-net** [comment]
Hold down the SHIFT key while booting from D0: (SDRIVE.ATR), then press "3" to start the version with help, and you get a key description by pressing the HELP key.

**Comment by kbr-net** [comment]
There are also the original docs available on Rasters website:
http://raster.infos.cz/atari/hw/sdrive/SDrive_en.pdf

**Comment by s-simpson** [comment]
https://atari8bit.net/everything-sdrive-max/

**Comment by s-simpson** [comment]
https://atariwiki.org/wiki/Wiki.jsp?page=SDrive-MAX

**Comment by s-simpson** [comment]
https://www.youtube.com/watch?v=-OshRXxzJTY
