### ISSUE TITLE
Screen autodetection still doesn't work in v1.2c2.

### ISSUE THREAD

**Issue by TzOk83** [kbr-net/sdrive-max#39]
Still no-go for screen auto detection with v1.2c2...

**Comment by kbr-net** [comment]
Could you post the output screen of eeprom_writer.hex please?

**Comment by TzOk83** [comment]
Here you have it (this is for ILI9340):
![obraz](https://user-images.githubusercontent.com/34161432/73529907-c8155800-4417-11ea-9aee-018497933e3b.png)

Colors are inverted, I can't pass touchscreen calibration.

**Comment by kbr-net** [comment]
Strange, this looks also like touchscreen is always pressed...
Does it work correctly with other arduino applications?

**Comment by TzOk83** [comment]
Yes, it works with the example sketches from MCUFriend_kbv, as well as with SDrive MAX v1.2b with swapped X and Y axes in touchscreen (configured like for HX8347G).

**Comment by kbr-net** [comment]
Could you please run this [eeprom_writer.hex.gz](https://github.com/kbr-net/sdrive-max/files/4140094/eeprom_writer.hex.gz), and show me the output?

**Comment by TzOk83** [comment]
Here you have:
![obraz](https://user-images.githubusercontent.com/34161432/73552596-cca63480-4448-11ea-9a1d-9b9aa968f687.png)

**Comment by kbr-net** [comment]
Damn, this looks correctly...

**Comment by TzOk83** [comment]
Maybe this will explain more:
![obraz](https://user-images.githubusercontent.com/34161432/73564921-e5badf80-4460-11ea-8b16-6ed7621310ad.png) 
![obraz](https://user-images.githubusercontent.com/34161432/73564936-ebb0c080-4460-11ea-9d62-f523abcb0bf0.png) 
![obraz](https://user-images.githubusercontent.com/34161432/73564941-f10e0b00-4460-11ea-8189-215c4ce3a0aa.png) 
![obraz](https://user-images.githubusercontent.com/34161432/73564954-f66b5580-4460-11ea-9500-28b0c7b5f573.png)

I believe this is not using EEPROM data, as this was executed with EEPROM content from a working v1.2b.

**Comment by kbr-net** [comment]
Thanks, but this does not matter, the values without touch are necessary.

**Comment by kbr-net** [comment]
Please try: 
[eeprom_writer.hex.gz](https://github.com/kbr-net/sdrive-max/files/4141327/eeprom_writer.hex.gz)

**Comment by TzOk83** [comment]
Touch now works, but colors are still in negative.

**Comment by kbr-net** [comment]
Hm, ok, then i have mixed something up...
I will release a new beta v12c3 soon, please test this again.

**Comment by TzOk83** [comment]
v12c3 flashed as ILI3941 seems to work ok (yet on boot I have message saying TFT-ID: 3940).
Thank you.

**Comment by kbr-net** [comment]
Ignore it, there are so much display variants in the wild, maybe production failures etc...
