### ISSUE TITLE
WAVGAT UNO R3

### ISSUE THREAD

**Issue by mamejay** [kbr-net/sdrive-max#51]
This is a silly question.  I accidentally purchased WAVGAT UNO R3 not realizing that they are not a direct clone.
I have tried to write the eeprom_writer.hex to the UNO and now its stuck in a loop failing on verify.
I cannot reflash any other firmware to the UNO as I get time out issues opening the port.
Any idea if I can make these usable with a SDRive Max and if possible how to recover the boot loop I have on it.

Thanks

**Comment by StmLord** [comment]
> This is a silly question. I accidentally purchased WAVGAT UNO R3 not realizing that they are not a direct clone.
> I have tried to write the eeprom_writer.hex to the UNO and now its stuck in a loop failing on verify.
> I cannot reflash any other firmware to the UNO as I get time out issues opening the port.
> Any idea if I can make these usable with a SDRive Max and if possible how to recover the boot loop I have on it.
> 
> Thanks

I have about 20 of these UNOs and up till now couldn't find a way to flash them.
Better get a proper atmega 328p clone

**Comment by mamejay** [comment]
I ended up desoldering the clone 328 chips and soldering in real ones.  Reflashed using another UNO that worked and now they all work corectly.

**Comment by kbr-net** [comment]
You have could used a ISP flash adapter instead.
