### ISSUE TITLE
eeprom_writer.hex missing from github, no instructions on dependencies required to build

### ISSUE THREAD

**Issue by e474** [kbr-net/sdrive-max#59]
You could save a lot of time and effort for other people by including eeprom_writer.hex.

**Comment by kbr-net** [comment]
Look at Releases, there is a eeprom_writer.hex for each display variant in the zip file. And the README says:

> Firmware programming:
> 
> First use the eeprom-writer.hex to set the correct values to the EEPROM!
> Wait until the writer has done, then program the SDrive.hex into the flash.
